// Copyright 2026 PneumaGe Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated from PneumaGe Device Descriptor Schema v1.0.0
// DO NOT EDIT THIS FILE MANUALLY
// Generated on: 2026-06-01T20:30:49.406Z

#ifndef DEVICE_DESCRIPTOR_H
#define DEVICE_DESCRIPTOR_H

#include <stdint.h>
#include <stdbool.h>

// Schema version
#define DEVICE_DESCRIPTOR_VERSION_MAJOR 1
#define DEVICE_DESCRIPTOR_VERSION_MINOR 0
#define DEVICE_DESCRIPTOR_VERSION_PATCH 0
#define DEVICE_DESCRIPTOR_VERSION "1.0.0"

// Array size limits
#define MAX_STRING_LENGTH 64
#define MAX_CAPABILITIES 8
#define MAX_SENSORS 8
#define MAX_CHANNELS_PER_SENSOR 8

// ==========================================
// DEVICE DESCRIPTOR STRUCTURES
// ==========================================

// Device Capabilities
enum class DeviceCapability {
  RANSAC_ONBOARD = 0,
  RANSAC_REMOTE = 1,
  MULTI_CHANNEL = 2,
  IMU_STABILIZATION = 3,
  GPS = 4,
};

// Sensor Types
enum class SensorType {
  NDIR = 0,
  MEMS = 1,
  ELECTROCHEMICAL = 2,
  PID = 3,
  THERMOCOUPLE = 4,
  RTD = 5,
};

// Channel Descriptor
struct __attribute__((packed)) ChannelDescriptor {
  char id[64];          // Unique channel identifier
  char name[64];        // Human-readable name
  char unit[64];        // Measurement unit
  char gasType[64];     // Target gas species (optional)
  float rangeMin;                          // Minimum measurement range
  float rangeMax;                          // Maximum measurement range
  float resolution;                        // Measurement resolution
  float precision;                         // Measurement precision
  float sampleRate;                        // Sampling frequency in Hz
  bool hasRange;                           // Whether range values are set
  bool hasResolution;                      // Whether resolution is set
  bool hasPrecision;                       // Whether precision is set
  bool hasSampleRate;                      // Whether sample rate is set
};

// Sensor Descriptor
struct __attribute__((packed)) SensorDescriptor {
  char id[64];          // Unique sensor identifier
  char make[64];        // Manufacturer
  char model[64];       // Model identifier
  char serialNumber[64];// Serial number
  SensorType sensorType;                   // Sensor technology type
  ChannelDescriptor channels[8];
  uint8_t channelCount;                    // Number of channels
};

// Pump Descriptor
struct __attribute__((packed)) PumpDescriptor {
  char make[64];        // Manufacturer
  char model[64];       // Model number
  char serialNumber[64];// Serial number (optional)
  float flowRateMin;                       // Minimum flow rate (L/min)
  float flowRateMax;                       // Maximum flow rate (L/min)
  bool hasFlowRate;                        // Whether flow rate values are set
};

// Top-level Device Descriptor
struct __attribute__((packed)) DeviceDescriptor {
  char deviceId[64];     // Unique device identifier
  char deviceName[64];   // Human-readable name
  uint16_t descriptorVersion;              // Descriptor format version
  char macAddress[18];                     // BLE MAC address (AA:BB:CC:DD:EE:FF)
  char processorMake[64];// Processor manufacturer
  char processorModel[64];// Processor model
  char processorSerial[64];// Processor serial
  char firmwareVersion[16];                // Firmware version (semver)
  char dataModelVersion[16];               // Compatible data model version
  DeviceCapability capabilities[8];
  uint8_t capabilityCount;                 // Number of capabilities
  PumpDescriptor pump;                     // Pump specification
  bool hasPump;                            // Whether pump is present
  SensorDescriptor sensors[8];
  uint8_t sensorCount;                     // Number of sensors
};

#endif // DEVICE_DESCRIPTOR_H
